import { Component, signal } from '@angular/core';
import { form, FormField } from '@angular/forms/signals';

export interface FaqItem{
  question: string,
  answer: string
}

@Component({
  selector: 'app-faq-page',
  imports: [FormField],
  templateUrl: './faq-page.html',
  styleUrl: './faq-page.css',
})
export class FaqPage {
  faqList: FaqItem[] = [
    {
      question: "why can’t I edit a pomodoro time unit?",
      answer: "On Pomo website, a pomodoro unit is and will always be of 25 minutes. This unit is the standard among the majority of pomodoro timers. It reppresents the so called \"sweet spot\" to be able to maintain focus without feeling overwhelmed or stressed. In this way people are able to study and concentrate for a longer period of time"
    },
    {
      question: "how can I use study zone and pomodoro timer effectively?",
      answer: "to be able to use study zone and pomodoro timer in the best possible way use two browser windows, one for the timer and one for the study zone, then you work by creating decks, cards and testing yourself on the study zone while in the timer is running on the other window of your browser in the background."
    },

    /* -- THESE QUESTIONS BELOW ARE GENERATED BY A.I. -- */
    {
      question: "how do I create a study deck?",
      answer: "From the study zone, click the button to create a new deck, give it a title, choose its layout if needed, and then add cards to start studying. Once created, you can open the deck and begin learning or reviewing your content."
    },
    {
      question: "can I edit or delete a deck after I create it?",
      answer: "Yes. In the study zone, you can open a deck’s settings to edit its information or remove it if you no longer need it. This helps you keep your study materials organized as your learning evolves."
    },
    {
      question: "what is the difference between the timer and the activity page?",
      answer: "The pomodoro timer helps you focus with timed work and break sessions, while the activity page is where you organize your study tasks and track progress on the things you want to complete. They work together to support both focus and planning."
    },
    {
      question: "how do I track my study progress?",
      answer: "You can track your study progress through the activity page, where your tasks and pomodoro completions are recorded, and through the study zone, where you can review decks and cards you have created or studied."
    },
    {
      question: "what happens when I complete a pomodoro cycle?",
      answer: "When a pomodoro session ends, the app records your time and either starts a short break, a long break, or returns to work depending on your timer settings and progress. If you selected an activity, that session can also be linked to it."
    },
    {
      question: "can I use the timer without an activity selected?",
      answer: "Yes. You can still use the pomodoro timer for focused study sessions even if you do not assign a specific activity. The activity feature is optional and mainly helps with tracking study goals and progress."
    },
    {
      question: "why do long breaks happen after several pomodoros?",
      answer: "Long breaks are built into the pomodoro technique to help prevent burnout and maintain concentration over long study sessions. They usually happen after a set number of completed pomodoros to give your brain a longer reset."
    },
    {
      question: "can I search for a specific deck or activity?",
      answer: "Yes. Both the study zone and the activity page include search tools that let you filter content by title or keyword, making it easier to find what you need quickly."
    },
    {
      question: "how do I customize the timer settings?",
      answer: "Open the timer settings from the timer page to adjust values such as break lengths and session frequency. These settings help you adapt the tool to your study rhythm and personal preferences."
    },
    {
      question: "what is the best way to use the app for studying?",
      answer: "A strong workflow is to plan your tasks in the activity page, focus with the pomodoro timer, and review or strengthen your knowledge using the study zone. This combination helps you stay organized while keeping your study sessions efficient."
    },
    {
      question: "can I access my profile and personal information?",
      answer: "Yes. The profile section lets you manage your personal information and check your account details, including your profile photo and settings related to your user account."
    },
    {
      question: "do I need to use every feature at the same time?",
      answer: "No. Pomo is designed to be flexible, so you can use the timer, the study zone, or the activities page separately depending on what you need at the moment. The app is meant to support your study routine, not complicate it."
    }
  ];
  faqToDisplay = signal<FaqItem[]>(this.faqList);

  /* search form init */
  formModel = signal({
    word: ''
  });
  searchForm = form(this.formModel);

  execSearch(){
    this.faqToDisplay.update(() =>
      this.faqList.filter((faq) => 
        faq.question.toLowerCase().includes(this.searchForm.word().value().toLowerCase()) ||
        faq.answer.toLowerCase().includes(this.searchForm.word().value().toLowerCase())
      )
    )
  }

  onSubmit(event: Event){
    event.preventDefault();
    this.execSearch();
  }
}
